### DISCUSSION TITLE
Please Provide an example of Agent communicates with multiple mcp servers with sse transport and choose right tool

### DISCUSSION THREAD

**Discussion by aubhadia** [evalstate/fast-agent#48] [General]
can you please provide an example of How fast Agent can communicate with multiple MCP servers with SSE transport and choose the right tool?

**Comment by evalstate** [comment]
Hi @aubhadia 

Here is an example config for Home Assistant via SSE - note v0.2.7 includes support for setting the headers:

```python title="hass.py"
import asyncio

from mcp_agent.core.fastagent import FastAgent
fast: FastAgent = FastAgent("Home Assistant Demo")


@fast.agent("hass",servers=["hass","prompts"],instruction="you have control of my house",model="sonnet")

async def main() -> None:
    # Use the app's context manager
    async with fast.run() as agent:
        await agent.interactive()


if __name__ == "__main__":
    asyncio.run(main())
```
```yaml 
mcp:
    hass:
      transport: sse
      url: http://192.168.5.9:8123/mcp_server/sse
      headers:
        Authorization: "Bearer XXXXXXX"
```

Works well, and easy to add additional servers. Does this help?
