### ISSUE TITLE
A way to debug errors within stdio MCP server?

### ISSUE THREAD

**Issue by Zombiehelp54** [evalstate/fast-agent#124]
This is my current MCP config: 
```
mcp:
    servers:
        Example:
            command: python3
            args: ["/root/mcp-mailer/main.py"]


```

Currently, if my MCP server has any issue that causes it to fail to start, the agent will not run and hangs without displaying any errors.
Also, if the MCP stops during runtime, the tool call just hangs forever. 

Is there a way to set a timeout for tool calls and also to debug errors happening within the STDIO MCP server (view the stderr maybe? )
