### ISSUE TITLE
Running w/o OpenAI causes 404 error

### ISSUE THREAD

**Issue by buddha314** [evalstate/fast-agent#145]
I am attempting to run fast-agent without Anthropic or OpenAI.  My config files are below.

I receive the following error that doesn't indicate which URL is begin attempted.

```
 hello
╭─────────────────────────────────────────────────────────────────────────────────────────────────────────── (default) [USER] ─╮
│                                                                                                                              │
│  hello                                                                                                                       │
│                                                                                                                              │
╰─ qwen3:06b turn 1 ───────────────────────────────────────────────────────────────────────────────────────────────────────────╯



default > [ERROR] 2025-05-07T07:40:46 mcp_agent.llm.providers.augmented_llm_openai.default - Error: 404 page not found
[mcp_agent.llm.providers.augmented_llm_openai.default] Error: 404 page not found
```

Ollama is running the agent responds in the Ollama console. The config file.
```
# FastAgent Configuration File

default_model: generic.qwen3:06b

fastmcp:
  client:
    timeout: 60  # seconds


# Set Anthropic to null to disable it completely
anthropic:
    api_key: null


generic:
    base_url: "http://localhost:11434"
    api_key: "ollama"

# Logging and Console Configuration:
logger:
    level: "info"
    type: "console"
    # level: "debug" | "info" | "warning" | "error"
    # type: "none" | "console" | "file" | "http"
    # path: "/path/to/logfile.jsonl"

    
    # Switch the progress display on or off
    progress_display: true

    # Show chat User/Assistant messages on the console
    show_chat: true
    # Show tool calls on the console
    show_tools: true
    # Truncate long tool responses on the console 
    truncate_tools: true
```

## UPDATE:

Viewing the log file it appears to be calling <ollama>/chat/completions. I'm guessing that's the 404, but I don't know how else to call Ollama.

```
{"level":"DEBUG","timestamp":"2025-05-07T07:33:18.184891","namespace":"mcp_agent.llm.providers.augmented_llm_openai.default","message":"Chat in progress","data":{"data":{"progress_action":"Chatting","model":"qwen3:06b","agent_name":"default","chat_turn":2}}}
{"level":"DEBUG","timestamp":"2025-05-07T07:33:20.448147","namespace":"mcp_agent.llm.providers.augmented_llm_openai.default","message":"OpenAI completion response:","data":{"data":{"request":{"method":"POST","url":{"_uri_reference":["http","","localhost",11434,"/chat/completions",null,null]},"headers":["host","accept-encoding","connection","accept","content-type","user-agent","x-stainless-lang","x-stainless-package-version","x-stainless-os","x-stainless-arch","x-stainless-runtime","x-stainless-runtime-version","authorization","x-stainless-async","x-stainless-retry-count","x-stainless-read-timeout","content-length"],"extensions":{"timeout":{"connect":5.0,"read":600,"write":"600","pool":"600"}},"stream":[{"capitalize":"<callable: capitalize>","center":"<callable: center>","count":"<callable: count>","decode":"<callable: decode>","endswith":"<callable: endswith>","expandtabs":"<callable: expandtabs>","find":"<callable: find>","fromhex":"<callable: fromhex>","hex":"<callable: hex>","index":"<callable: index>","isalnum":"<callable: isalnum>","isalpha":"<callable: isalpha>","isascii":"<callable: isascii>","isdigit":"<callable: isdigit>","islower":"<callable: islower>","isspace":"<callable: isspace>","istitle":"<callable: istitle>","isupper":"<callable: isupper>","join":"<callable: join>","ljust":"<callable: ljust>","lower":"<callable: lower>","lstrip":"<callable: lstrip>","maketrans":"<callable: maketrans>","partition":"<callable: partition>","removeprefix":"<callable: removeprefix>","removesuffix":"<callable: removesuffix>","replace":"<callable: replace>","rfind":"<callable: rfind>","rindex":"<callable: rindex>","rjust":"<callable: rjust>","rpartition":"<callable: rpartition>","rsplit":"<callable: rsplit>","rstrip":"<callable: rstrip>","split":"<callable: split>","splitlines":"<callable: splitlines>","startswith":"<callable: startswith>","strip":"<callable: strip>","swapcase":"<callable: swapcase>","title":"<callable: title>","translate":"<callable: translate>","upper":"<callable: upper>","zfill":"<callable: zfill>"}],"_content":"b'{\"messages\":[{\"role\":\"system\",\"content\":\"You are a helpful AI Agent\"},{\"role\":\"system\",\"content\":\"You are a helpful AI Agent\"},{\"role\":\"user\",\"content\":\"hello\"},{\"role\":\"user\",\"content\":\"hello\"}],\"model\":\"qwen3:06b\",\"max_tokens\":2048,\"tools\":null}'"},"message":"404 page not found","body":"404 page not found","code":null,"param":null,"type":null,"response":"<httpx.Response [404] http://localhost:11434/chat/completions>","status_code":404,"request_id":null}}}
{"level":"ERROR","timestamp":"2025-05-07T07:33:20.448147","namespace":"mcp_agent.llm.providers.augmented_llm_openai.default","message":"Error: 404 page not found"}
```

**Comment by buddha314** [comment]
Ai chihuahua, so you need the "/v1" at the end. Got to this via this ticket https://github.com/evalstate/fast-agent/issues/40 

New config seems to work

```
# FastAgent Configuration File

# Default Model Configuration:
# 
# Takes format:
#   <provider>.<model_string>.<reasoning_effort?> (e.g. anthropic.claude-3-5-sonnet-20241022 or openai.o3-mini.low)
# Accepts aliases for Anthropic Models: haiku, haiku3, sonnet, sonnet35, opus, opus3
# and OpenAI Models: gpt-4.1, gpt-4.1-mini, o1, o1-mini, o3-mini
#
# If not specified, defaults to "haiku". 
# Can be overriden with a command line switch --model=<model>, or within the Agent constructor.

default_model: generic.qwen3:0.6b

fastmcp:
  client:
    timeout: 60  # seconds


# Set Anthropic to null to disable it completely
anthropic:
    api_key: null


generic:
    base_url: "http://localhost:11434/v1"
    api_key: "ollama"

# Logging and Console Configuration:
logger:
    level: "debug"
    type: "file"
    path: "error.jsonl"
    # level: "debug" | "info" | "warning" | "error"
    # type: "none" | "console" | "file" | "http"
    # path: "/path/to/logfile.jsonl"

    
    # Switch the progress display on or off
    progress_display: true

    # Show chat User/Assistant messages on the console
    show_chat: true
    # Show tool calls on the console
    show_tools: true
    # Truncate long tool responses on the console 
    truncate_tools: true
```
