### ISSUE TITLE
Can you load  Authorization: "Bearer <secret>" from ENV variables or passed to the agent ?

### ISSUE THREAD

**Issue by xxradar** [evalstate/fast-agent#163]
Hi, wondering if fast-agent in the case can be loaded from a env variable or passed in the code of the agent ?

Maybe I'm just overlooking sorry.

```
The documetation states that <secret> can be stored in fastagent.secrets.yaml.
mcp:
# name used in agent servers array
  server_two:
    transport: "http"
    # url to connect
    url: "http://localhost:8000/mcp"
    # timeout in seconds to use for sse sessions (optional)
    read_transport_sse_timeout_seconds: 300
    # request headers for connection
    headers: 
          Authorization: "Bearer <secret>"

# name used in agent servers array
  server_three:
    transport: "sse"
    # url to connect
    url: "http://localhost:8001/sse"
```
