### ISSUE TITLE
Where are the "configuration files" mentioned in the readme for Windows?

### ISSUE THREAD

**Issue by XDcsy** [evalstate/fast-agent#17]
> Windows Users - there are a couple of configuration changes needed for the Filesystem and Docker MCP Servers - necessary changes are detailed within the configuration files.

Where are the configuration files and how to change them? I have checked the `fastagent.config` file and `agent.py` but did not find instructions on this.

**Comment by evalstate** [comment]
Hi @XDcsy -- the changes are needed in `fastagent.config.yaml` for some of the examples:
 - MCP Servers that use NPX
 - Docker Containers that use a mapped volume.

For example if you `fast-agent bootstrap data-analysis` it will generate a new folder, with a `fastagent.config.yaml`. Inside there are instructions (snippet reproduced below):

```
    filesystem:
      # On windows update the command and arguments to use `node` and the absolute path to the server.
      # Use `npm i -g @modelcontextprotocol/server-filesystem` to install the server globally.
      # Use `npm -g root` to find the global node_modules path.`
      # command: "node"
      # args: ["c:/Program Files/nodejs/node_modules/@modelcontextprotocol/server-filesystem/dist/index.js","."]
      command: "npx"
      args: ["-y", "@modelcontextprotocol/server-filesystem", "./mount-point/"]

```
 
Often commenting/uncommenting the examples there will work.
