### ISSUE TITLE
/prompts and /prompt will only return the prompts available to the first agent the interactive prompt selected

### ISSUE THREAD

**Issue by wreed4** [evalstate/fast-agent#177]
When using an interactive prompt, the "/prompts" and "/prompt" commands will only show (and allow you to use) prompts that are available to the first agent the prompt opens with.  This persists after switching agents.  Since the first agent that the prompt is talking to is not necessarily deterministic, this means that not all prompts are available at all on some runs. 

I looked through the code only briefly and I see we're passing in list_prompts functions into several places.  I anticipate what's happening is a particular agent's list_prompts function is being passed and bound at the beginning of the interactive loop and so it persists throughout the loop.  I haven't found exactly where yet though.

**Comment by evalstate** [comment]
As baseline I've tried following:

```
mcp:
  servers:
    prompt1:
      command: "prompt-server"
      args: ["prompt_one.txt"]
    prompt2:
      command: "prompt-server"
      args: ["prompt_two.txt"]
```

`fast-agent go --servers=prompt1,prompt2`

And can see both prompts:

![Image](https://github.com/user-attachments/assets/4eeb58f1-b0b8-486d-819b-7b676f17bb31)
