### ISSUE TITLE
How to run post-processing/transformation of a response that agent received from MCP server?

### ISSUE THREAD

**Issue by REASY** [evalstate/fast-agent#250]
Hello, 

I want to have a way to transform a response that Agent got from a call to MCP to some other format before passing it to LLM. An example code
```python
@fast.agent(
    name="network",
    instruction="""You are an agent with read-only access to Kubernetes that handles networking related issues. Check the state of all network-related objects in Kubernetes and report their statuses""",
    servers=["kubernetes"],
    model="gpt-4.1",
)
```

fastagent.config.yaml:
```yaml
mcp:
  servers:
      kubernetes:
          transport: "http"
          # url to connect
          url: "http://127.0.0.1:9000/mcp"
          # timeout in seconds to use for sse sessions (optional)
          read_transport_sse_timeout_seconds: 300
```
I see [AugmentedLLM.post_tool_call](https://github.com/evalstate/fast-agent/blob/main/src/mcp_agent/llm/augmented_llm.py#L467) but it is quite deep inside... Is there a more elegant or standard way? Thanks
