### ISSUE TITLE
Sampling issue

### ISSUE THREAD

**Issue by JagjeevanAK** [evalstate/fast-agent#87]
Hi everyone,

I’m currently in the process of setting up the Fast Agent and testing my MCP server using the Gemini API. However, I’m encountering some errors during testing.

Could anyone help me understand how to debug this issue? I'm wondering if I might be missing a configuration step, or if there could be a problem with the Gemini API or in MCP server itself. Any guidance would be greatly appreciated!

I have made sampling with reference to Official documentation.

Thanks in advance!

<img width="1351" alt="Image" src="https://github.com/user-attachments/assets/764a565a-e863-48e7-879c-f1177871edaa" />

current sampling setup :

```Typescript
import { CreateMessageResult } from "@modelcontextprotocol/sdk/types.js";
import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { z } from "zod";


export interface SamplingRequest {
  messages: Array<{
    role: "user" | "assistant";
    content: {
      type: "text" | "image";
      text?: string;
      data?: string;
      mimeType?: string;
    }
  }>;
  modelPreferences?: {
    hints?: Array<{
      name?: string;
    }>;
    costPriority?: number;
    speedPriority?: number;
    intelligencePriority?: number;
  };
  systemPrompt?: string;
  includeContext?: "none" | "thisServer" | "allServers";
  temperature?: number;
  maxTokens: number;
  stopSequences?: string[];
  metadata?: Record<string, unknown>;
}

/**
 * Request a completion from an LLM via the connected client
 * 
 * @param mcpServer MCP server instance
 * @param request Sampling request parameters
 * @returns The LLM completion response
 */

const CreateMessageResultSchema = z.object({
    model: z.string(),
    stopReason: z.string().optional(),
    role: z.enum(["user", "assistant"]),
    content: z.object({
        type: z.enum(["text", "image"]),
        text: z.string().optional(),
        data: z.string().optional(),
        mimeType: z.string().optional(),
    }),
});

export async function requestSampling(
  mcpServer: McpServer,
  request: SamplingRequest
): Promise<CreateMessageResult> {
  try {
    // Access the underlying Server instance from McpServer
    const response = await mcpServer.server.request({
      method: "sampling/createMessage",
      params: {
        messages: request.messages,
        modelPreferences: request.modelPreferences,
        systemPrompt: request.systemPrompt,
        includeContext: request.includeContext,
        temperature: request.temperature,
        maxTokens: request.maxTokens,
        stopSequences: request.stopSequences,
        metadata: request.metadata
      }
    }, CreateMessageResultSchema);
    
    return response as CreateMessageResult;
  } catch (error: unknown) {
    const errorMessage = error instanceof Error ? error.message : String(error);
    throw new Error(`Sampling request failed: ${errorMessage}`);
  }
}

```

**Comment by evalstate** [comment]
Can you show me the section in fastagent.config.yaml where sampling is defined:
```yaml
mcp:
  servers:
    sampling_resource_openai:
      command: "uv"
      args: ["run", "sampling_resource_server.py"]
      sampling:
        model: "gpt-4o-mini"
```

I've just run the e2e tests with a couple of different models OK, so would like to reproduce.

**Comment by JagjeevanAK** [comment]
```YML
# FastAgent Configuration File

# Default Model Configuration:
# 
# Takes format:
#   <provider>.<model_string>.<reasoning_effort?> (e.g. anthropic.claude-3-5-sonnet-20241022 or openai.o3-mini.low)
# Accepts aliases for Anthropic Models: haiku, haiku3, sonnet, sonnet35, opus, opus3
# and OpenAI Models: gpt-4o-mini, gpt-4o, o1, o1-mini, o3-mini
#
# If not specified, defaults to "haiku". 
# Can be overriden with a command line switch --model=<model>, or within the Agent constructor.

default_model: generic.gemini-2.0-flash


generic:
    base_url: "https://generativelanguage.googleapis.com/v1beta/openai/"

# Logging and Console Configuration:
logger:
    # level: "debug" | "info" | "warning" | "error"
    # type: "none" | "console" | "file" | "http"
    # path: "/path/to/logfile.jsonl"

    
    # Switch the progress display on or off
    progress_display: true

    # Show chat User/Assistant messages on the console
    show_chat: true
    # Show tool calls on the console
    show_tools: true
    # Truncate long tool responses on the console 
    truncate_tools: true

# MCP Servers
mcp:
    servers:
        fetch:
            command: "uvx"
            args: ["mcp-server-fetch"]
        filesystem:
            command: "npx"
            args: ["-y", "@modelcontextprotocol/server-filesystem", "."]
        openfoodfacts:
            command: "npx"
            args: ["-y", "@jagjeevan/openfoodfacts-mcp@latest", "--developer"]
            env:
                TRANSPORT: "stdio"
            sampling:
                model: "generic.gemini-2.0-flash"
```

**Comment by evalstate** [comment]
![Image](https://github.com/user-attachments/assets/6aeef0d9-f7e2-402c-bffe-1c23af5dc6c4)
OK - this seems to be working my end with 0.2.14 - BUT - i want to double check the API key handling in this build. The prompt i used to trigger the tool was `generate recipe suggestions for milk and teabag`, and i got the tool call followed by sampling responses.

can you let me know what fast-agent version you currently have?

**Comment by evalstate** [comment]
Oh, amazing MCP Server by the way!

**Comment by JagjeevanAK** [comment]
Thankyou sir.

currently I am using gemini as I think that they don't support MCP compared to chatgpt and sonnet.

**Comment by JagjeevanAK** [comment]
Can you share your setup ?? I might be missing something

**Comment by evalstate** [comment]
```
import asyncio
from mcp_agent.core.fastagent import FastAgent
from mcp_agent.core.request_params import RequestParams

# Create the application
fast = FastAgent("fast-agent example")


# Define the agent
@fast.agent(
    instruction="You are a helpful AI Agent",
    servers=["openfoodfacts"],
    request_params=RequestParams(parallel_tool_calls=False),
)
async def main():
    # use the --model command line switch or agent arguments to change model
    async with fast.run() as agent:
        await agent.interactive()


if __name__ == "__main__":
    asyncio.run(main())

```

```
default_model: generic.gemini-2.0-flash

# Logging and Console Configuration:
logger:
  # Switch the progress display on or off
  progress_display: true

  # Show chat User/Assistant messages on the console
  show_chat: true
  # Show tool calls on the console
  show_tools: true
  # Truncate long tool responses on the console
  truncate_tools: true

# MCP Servers
mcp:
  servers:
    openfoodfacts:
      command: "npx"
      args: ["-y", "@jagjeevan/openfoodfacts-mcp@latest", "--developer"]
      env:
        TRANSPORT: "stdio"
      sampling:
        model: "generic.gemini-2.0-flash"
generic:
  base_url: "https://generativelanguage.googleapis.com/v1beta/openai/"
```

this is with build 0.2.14. i needed to set the OPENAI_API_KEY (i think due to a possible regression that i'm investigating now). 

![Image](https://github.com/user-attachments/assets/a48689be-707f-4400-9326-5ebdf6c34215)
